version: "3.7"
services:
  db:
    image: mysql:5.7
    restart: always
    container_name: mysql-test
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=test
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
